import 'server-only';
import { createReadStream } from 'node:fs';
import { mkdir, readFile, stat, unlink, writeFile } from 'node:fs/promises';
import { dirname, isAbsolute, join, resolve, sep } from 'node:path';
import { Readable } from 'node:stream';
import type { ByteRange, ObjectMetadata, StorageDriver } from './types';
import { StorageError } from './types';

/**
 * Local-disk driver for development and small single-server deployments.
 *
 * The base directory defaults to ./storage, which is outside Next's public
 * folder and is git-ignored, so nothing written here is ever served statically.
 */
export class LocalStorageDriver implements StorageDriver {
  readonly name = 'LOCAL' as const;
  private readonly baseDir: string;

  constructor(baseDir: string) {
    this.baseDir = isAbsolute(baseDir) ? baseDir : resolve(process.cwd(), baseDir);
  }

  async put(key: string, data: Buffer, _contentType: string): Promise<void> {
    const target = this.resolveKey(key);
    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, data, { flag: 'wx' }).catch(async (error: NodeJS.ErrnoException) => {
      // A colliding key means the CSPRNG produced a duplicate, which should be
      // impossible — surface it rather than silently overwriting a file.
      if (error.code === 'EEXIST') {
        throw new StorageError(`Storage key already exists: ${key}`);
      }
      throw new StorageError('Could not write the uploaded file.', error);
    });
  }

  async head(key: string): Promise<ObjectMetadata | null> {
    try {
      const stats = await stat(this.resolveKey(key));
      if (!stats.isFile()) return null;
      return { size: stats.size, contentType: null, lastModified: stats.mtime };
    } catch {
      return null;
    }
  }

  async getBuffer(key: string): Promise<Buffer> {
    try {
      return await readFile(this.resolveKey(key));
    } catch (error) {
      throw new StorageError('Could not read the stored file.', error);
    }
  }

  async getStream(key: string, range?: ByteRange): Promise<ReadableStream<Uint8Array>> {
    const path = this.resolveKey(key);
    const nodeStream = range
      ? createReadStream(path, { start: range.start, end: range.end })
      : createReadStream(path);

    // Readable.toWeb returns the DOM ReadableStream a Response body expects.
    return Readable.toWeb(nodeStream) as ReadableStream<Uint8Array>;
  }

  async delete(key: string): Promise<void> {
    try {
      await unlink(this.resolveKey(key));
    } catch (error) {
      const code = (error as NodeJS.ErrnoException).code;
      if (code === 'ENOENT') return; // already gone — deletion is idempotent
      throw new StorageError('Could not delete the stored file.', error);
    }
  }

  /**
   * Path-traversal guard. Keys are generated by the application, but this
   * function is the last line between a key and the filesystem, so it verifies
   * rather than trusts: the resolved path must sit inside the base directory.
   */
  private resolveKey(key: string): string {
    if (!/^[A-Za-z0-9][A-Za-z0-9/_.-]*$/.test(key) || key.includes('..')) {
      throw new StorageError(`Rejected unsafe storage key: ${key}`);
    }

    const target = resolve(join(this.baseDir, key));
    const root = resolve(this.baseDir);

    if (target !== root && !target.startsWith(root + sep)) {
      throw new StorageError(`Rejected storage key outside the base directory: ${key}`);
    }

    return target;
  }
}
