import type { Metadata } from 'next';
import Link from 'next/link';
import { redirect } from 'next/navigation';
import { CheckCircle2, HelpCircle, KeyRound } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Alert, Badge } from '@/components/ui/feedback';
import { guardStudent } from '@/lib/auth/guards';
import { prisma } from '@/lib/db';
import { ACCESS_CODE_STATUS } from '@/lib/constants';
import { formatDate } from '@/lib/utils';
import { ActivateForm } from './activate-form';

export const metadata: Metadata = { title: 'Activate your account' };

export default async function ActivatePage() {
  const user = await guardStudent();

  if (user.student?.isActivated) {
    redirect('/student');
  }

  // We can tell the student whether a code has been issued to them — and when
  // it expires — without ever revealing the code itself, which is stored only
  // as a hash.
  const pendingCode = await prisma.accessCode.findFirst({
    where: { studentId: user.id, status: ACCESS_CODE_STATUS.ACTIVE },
    orderBy: { createdAt: 'desc' },
    select: { codePrefix: true, codeLast4: true, expiresAt: true, createdAt: true },
  });

  return (
    <div className="mx-auto max-w-lg py-4">
      <div className="text-center">
        <span
          className="mx-auto mb-5 grid size-16 place-items-center rounded-2xl bg-brand-50 text-brand-700 dark:bg-brand-950 dark:text-brand-300"
          aria-hidden
        >
          <KeyRound className="size-7" />
        </span>
        <h1 className="font-display text-2xl font-extrabold tracking-tight">
          Enter your access code
        </h1>
        <p className="mt-2 text-sm text-[var(--text-muted)]">
          Your school issues one code to you personally. Enter it once and your
          subjects, lessons and examinations open straight away.
        </p>
      </div>

      {!user.student?.classId ? (
        <Alert tone="warn" className="mt-6" title="Choose your class first">
          <p>Your code is tied to a class, so tell us which class you are in.</p>
          <Button asChild size="sm" variant="secondary" className="mt-3">
            <Link href="/student/select-class">Choose my class</Link>
          </Button>
        </Alert>
      ) : null}

      {pendingCode ? (
        <Alert tone="success" className="mt-6" title="A code is waiting for you">
          <p>
            Your teacher issued a code on {formatDate(pendingCode.createdAt)}. It
            starts with{' '}
            <span className="font-mono font-bold">{pendingCode.codePrefix}-</span>{' '}
            and ends in{' '}
            <span className="font-mono font-bold">{pendingCode.codeLast4}</span>.
          </p>
          <p className="mt-1 text-xs opacity-90">
            It expires on {formatDate(pendingCode.expiresAt)}. Ask your teacher
            for the full code — nobody at the school can read it back from the
            system, so if it is lost they will issue a new one.
          </p>
        </Alert>
      ) : null}

      <Card className="mt-6">
        <CardContent className="py-6">
          <ActivateForm disabled={!user.student?.classId} />
        </CardContent>
      </Card>

      <section className="mt-8">
        <h2 className="flex items-center gap-2 text-sm font-bold text-[var(--text-strong)]">
          <HelpCircle className="size-4" aria-hidden />
          Common questions
        </h2>
        <dl className="mt-3 space-y-3 text-sm">
          <Faq
            term="I do not have a code."
            description="Ask your class teacher or the school office. Codes are issued by the school, never generated by students."
          />
          <Faq
            term="My friend gave me their code."
            description="It will not work. Every code is locked to one account and is refused for anyone else."
          />
          <Faq
            term="It says my code has expired."
            description="Codes stop working after their expiry date. Ask for a fresh one — it takes a moment to issue."
          />
        </dl>
      </section>

      <div className="mt-8 rounded-[var(--radius-card)] border border-dashed border-[var(--line-strong)] p-5">
        <p className="mb-3 text-xs font-semibold uppercase tracking-wide text-[var(--text-muted)]">
          What opens after activation
        </p>
        <ul className="space-y-2 text-sm text-[var(--text-body)]">
          {[
            'All the lessons for your class — videos, audio, PDFs and presentations',
            'Examinations set for your class, with your results afterwards',
            'Your class forum, where you can ask questions and help others',
          ].map((item) => (
            <li key={item} className="flex gap-2">
              <CheckCircle2
                className="mt-0.5 size-4 shrink-0 text-success-600"
                aria-hidden
              />
              {item}
            </li>
          ))}
        </ul>
        {user.student?.className ? (
          <Badge tone="brand" className="mt-4">
            {user.student.className}
          </Badge>
        ) : null}
      </div>
    </div>
  );
}

function Faq({ term, description }: { term: string; description: string }) {
  return (
    <div className="rounded-[var(--radius-field)] border border-[var(--line-soft)] p-3.5">
      <dt className="font-semibold text-[var(--text-strong)]">{term}</dt>
      <dd className="mt-0.5 text-[var(--text-muted)]">{description}</dd>
    </div>
  );
}
